### ISSUE TITLE
Can this be used with Jetson Nano?

### ISSUE THREAD

**Issue by atorsvn** [Vennify-Inc/chatting-transformer#22]
I get this error after a pip install on a Jetson Nano 2GB running debian:

ERROR: Could not find a version that satisfies the requirement chattingstransformer
ERROR: No matching distribution found for chattingstransformer

**Comment by EricFillion** [comment]
Hi! 

It looks like you made a small typo. Try changing "chattings" to "chatting"

**Comment by atorsvn** [comment]
Haha! Dear Technological singularity... Im a moron. Thanks!

**Comment by EricFillion** [comment]
> Haha! Dear Technological singularity... Im a moron. Thanks!

No worries! Combining Chatting Transformer with a Jetson Nano sounds really interesting. Please share your project if you ever create online content for it :)
